/**
 * StudyFlow AI — Offline Rule Engine
 * ─────────────────────────────────────────────────────────────
 * FEATURE 10: AI Offline Mode
 *
 * Provides deterministic, rule-based fallbacks for every AI-generated
 * output shape used by ProviderManager. When BOTH Gemini and Groq fail
 * (no internet, no API keys, rate limits, etc.), ProviderManager calls
 * into this engine instead of throwing — so task generation, scheduling,
 * replanning, coaching, and recommendations continue to work fully offline.
 *
 * Design principles:
 *  - No network calls, ever.
 *  - Output shapes EXACTLY match the validated shapes ProviderManager
 *    returns from Gemini/Groq, so callers require zero changes.
 *  - Every result includes provider: 'offline' so the UI can show
 *    a "🌐 Offline Mode" badge instead of "via gemini"/"via groq".
 */

'use strict';

const CATEGORIES = [
  'Python', 'JavaScript', 'DSA', 'Aptitude',
  'Communication', 'Projects', 'Exercise', 'Revision', 'Mock Tests'
];

class OfflineEngine {
  static name = 'offline';

  // ═══════════════════════════════════════════════════════════════════════
  // MODULE 4 FALLBACK — SMART TASK CREATION
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Converts a free-text prompt into a task array using keyword matching.
   * Detects category names and synonyms, extracts time hints, and detects
   * "tomorrow" for due_date. Falls back to a single Revision task if
   * nothing is detected, so the user always gets at least one result.
   *
   * @param {string} userPrompt
   * @param {object|null} context - db.getAIContextSummary()
   * @returns {{ tasks: Array, provider: string }}
   */
  static generateTasks(userPrompt, context = null) {
    const today = new Date().toISOString().slice(0, 10);
    const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
    const text = (userPrompt || '').toLowerCase();

    const keywordMap = {
      DSA: ['dsa', 'data structure', 'algorithm', 'leetcode', 'coding problem'],
      Python: ['python', 'py ', 'django', 'flask', 'pandas'],
      JavaScript: ['javascript', ' js ', 'js,', 'node', 'react', 'vue', 'typescript'],
      Aptitude: ['aptitude', 'quant', 'reasoning', 'logical', 'verbal'],
      Communication: ['communication', 'speaking', 'interview prep', 'soft skill', 'english', 'presentation'],
      Projects: ['project', 'build', 'portfolio', 'deploy', 'develop'],
      Exercise: ['exercise', 'workout', 'gym', 'run', 'walk', 'fitness'],
      Revision: ['revision', 'revise', 'review notes', 'recap', 'notes'],
      'Mock Tests': ['mock test', 'mock exam', 'practice test', 'full test', 'sample paper']
    };

    const detected = [];
    for (const [category, keywords] of Object.entries(keywordMap)) {
      if (keywords.some(kw => text.includes(kw))) {
        detected.push(category);
      }
    }

    // Extract time hints
    let totalMinutes = 60;
    const hourMatch = text.match(/(\d+(?:\.\d+)?)\s*hour/);
    const minMatch = text.match(/(\d+)\s*min/);
    if (hourMatch) totalMinutes = Math.round(parseFloat(hourMatch[1]) * 60);
    else if (minMatch) totalMinutes = parseInt(minMatch[1], 10);

    const dueDate = text.includes('tomorrow') ? tomorrow : today;

    // Use AI memory context if nothing detected
    let categories = detected;
    if (categories.length === 0 && context?.productiveCategories?.length) {
      categories = context.productiveCategories.slice(0, 2);
    }
    if (categories.length === 0) {
      categories = ['Revision'];
    }

    const perTaskMinutes = Math.max(15, Math.round(totalMinutes / categories.length));

    const titleMap = {
      DSA: 'DSA Practice',
      Python: 'Python Practice',
      JavaScript: 'JavaScript Practice',
      Aptitude: 'Aptitude Practice',
      Communication: 'Communication Practice',
      Projects: 'Project Work',
      Exercise: 'Exercise Session',
      Revision: 'Revision Session',
      'Mock Tests': 'Mock Test'
    };

    const tasks = categories.map((category, i) => ({
      title: titleMap[category] || `${category} Session`,
      category: CATEGORIES.includes(category) ? category : 'Revision',
      priority: i === 0 ? 'high' : 'medium',
      due_date: dueDate,
      estimated_minutes: perTaskMinutes,
      reminder_time: '',
      notes: 'Generated by Offline Mode — no AI provider available.',
      is_recurring: 0,
      recurrence_pattern: null
    }));

    return { tasks, provider: OfflineEngine.name };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // QUICK SESSION PLANNER
  // ═══════════════════════════════════════════════════════════════════════

  static generateQuickSession(userPrompt, context = null) {
    const text = (userPrompt || '').toLowerCase();
    
    // Extract time hints
    let totalMinutes = 60;
    const hourMatch = text.match(/(\d+(?:\.\d+)?)\s*hour/);
    const minMatch = text.match(/(\d+)\s*min/);
    if (hourMatch) totalMinutes = Math.round(parseFloat(hourMatch[1]) * 60);
    else if (minMatch) totalMinutes = parseInt(minMatch[1], 10);

    const segments = [];
    if (totalMinutes <= 25) {
      segments.push({ startMin: 0, endMin: totalMinutes, activity: 'Quick Review & Notes' });
    } else if (totalMinutes <= 45) {
      segments.push({ startMin: 0, endMin: 10, activity: 'Review previous concepts' });
      segments.push({ startMin: 10, endMin: totalMinutes, activity: 'Deep study / Problem solving' });
    } else {
      segments.push({ startMin: 0, endMin: 15, activity: 'Review previous notes' });
      segments.push({ startMin: 15, endMin: totalMinutes - 10, activity: 'Deep study / Practice' });
      segments.push({ startMin: totalMinutes - 10, endMin: totalMinutes, activity: 'Review mistakes & recap' });
    }

    return { segments, provider: OfflineEngine.name };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // MODULE 2 FALLBACK — AI TIMETABLE GENERATOR
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Builds a structured daily schedule with warmup, alternating study
   * and break blocks, exercise, revision, and wind-down — matching the
   * same output shape that ProviderManager returns from Gemini/Groq.
   *
   * @param {object} params
   * @param {number} params.hours
   * @param {string} params.energy - "low"|"medium"|"high"
   * @param {string[]} params.priorities
   * @param {string} params.startTime - "HH:MM"
   * @returns {{ schedule: Array, provider: string }}
   */
  static generateSchedule({ hours = 4, energy = 'medium', priorities = [], startTime = '18:00' }) {
    const schedule = [];
    const [sh, sm] = (startTime || '18:00').split(':').map(Number);
    let cur = sh * 60 + (sm || 0);
    const isLateNight = sh >= 22 || sh < 5; // 10 PM – 5 AM: no exercise/warmup

    const studyBlock = energy === 'high' ? 60 : energy === 'low' ? 25 : 45;
    const breakBlock = energy === 'high' ? 10 : 15;

    const defaults = [
      'DSA', 'Python', 'JavaScript', 'Aptitude',
      'Communication', 'Projects', 'Revision'
    ];
    const cats = priorities.length > 0
      ? [...priorities, ...defaults.filter(c => !priorities.includes(c))]
      : defaults;

    const fmt = (m) => {
      const h = Math.floor(m / 60) % 24;
      const mins = m % 60;
      return `${String(h).padStart(2, '0')}:${String(mins).padStart(2, '0')}`;
    };

    // Warmup block — skipped late at night (nobody needs a wake-up warmup
    // right before bed, and it displaces time that should go to winding down).
    if (!isLateNight) {
      schedule.push({
        time: fmt(cur),
        activity: '☀️ Warmup & Quick Review',
        duration: 15,
        type: 'warmup'
      });
      cur += 15;
    }

    const totalStudyMinutes = Math.max(30, Math.floor(hours * 60 * 0.70));
    let used = 0;
    let catIdx = 0;
    let consecutiveStudy = 0;

    while (used < totalStudyMinutes) {
      const remaining = totalStudyMinutes - used;
      const blockLen = Math.min(studyBlock, remaining);
      const cat = cats[catIdx % cats.length];

      schedule.push({
        time: fmt(cur),
        activity: `📚 ${cat}`,
        duration: blockLen,
        type: 'study'
      });
      cur += blockLen;
      used += blockLen;
      consecutiveStudy += blockLen;
      catIdx++;

      if (used < totalStudyMinutes && consecutiveStudy >= studyBlock) {
        schedule.push({
          time: fmt(cur),
          activity: '☕ Short Break',
          duration: breakBlock,
          type: 'break'
        });
        cur += breakBlock;
        consecutiveStudy = 0;
      }
    }

    // Exercise block — skipped late at night for the same reason as warmup.
    if (!isLateNight) {
      schedule.push({
        time: fmt(cur),
        activity: '🏃 Exercise / Walk',
        duration: 20,
        type: 'exercise'
      });
      cur += 20;
    }

    // Revision block — always the last active block, never warmup, so the
    // session winds down into review rather than starting-feeling activity.
    schedule.push({
      time: fmt(cur),
      activity: '🔁 Revision & Notes Review',
      duration: 20,
      type: 'revision'
    });
    cur += 20;

    // Wind-down
    schedule.push({
      time: fmt(cur),
      activity: '🌙 Wind Down & Plan Tomorrow',
      duration: 10,
      type: 'break'
    });

    return { schedule, provider: OfflineEngine.name };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // MODULE 5 FALLBACK — ADAPTIVE REPLANNING
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Applies rule-based adjustments to today's tasks based on the user's
   * instruction text. Keyword matching handles the most common cases:
   * tired/reduce, meeting/urgent, and move <category>.
   *
   * @param {string} instruction
   * @param {Array} currentTasks
   * @returns {{ tasks: Array, summary: string, provider: string }}
   */
  static generateReplan(instruction, currentTasks = []) {
    const text = (instruction || '').toLowerCase();
    const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);

    if (currentTasks.length === 0) {
      return {
        tasks: [],
        summary: "You don't have any pending tasks today to adjust.",
        provider: OfflineEngine.name
      };
    }

    const result = currentTasks.map(t => ({
      id: t.id,
      title: t.title,
      category: t.category,
      priority: t.priority,
      due_date: t.due_date,
      notes: t.notes || '',
      action: 'keep'
    }));

    let summary;

    if (text.includes('tired') || text.includes('reduce') || text.includes('lighter') || text.includes('burnout')) {
      // Demote all high → medium; move the bottom third to tomorrow
      result.forEach(t => {
        if (t.priority === 'high') t.priority = 'medium';
      });

      const maxToMove = Math.max(1, Math.floor(result.length / 3));
      let moved = 0;
      for (const t of result) {
        if (moved >= maxToMove) break;
        if (t.action === 'keep' && t.priority !== 'high') {
          t.action = 'move_tomorrow';
          t.due_date = tomorrow;
          moved++;
        }
      }

      summary = moved > 0
        ? `Understood — I've eased today's plan by moving ${moved} task${moved > 1 ? 's' : ''} to tomorrow and softening some priorities. Rest well!`
        : `Got it — I've lowered today's priorities slightly. Take it one step at a time.`;

    } else if (
      text.includes('meeting') || text.includes('urgent') ||
      text.includes('busy') || text.includes('event')
    ) {
      // Move the last task to tomorrow (simplest conflict-avoidance)
      const last = result[result.length - 1];
      if (last) {
        last.action = 'move_tomorrow';
        last.due_date = tomorrow;
        summary = `Noted — I've moved "${last.title}" to tomorrow to make room for your commitment today.`;
      } else {
        summary = `Noted — your schedule looks manageable as-is.`;
      }

    } else if (text.includes('move') || text.includes('reschedule') || text.includes('postpone')) {
      // Move tasks whose category name appears in the instruction
      const matchedCats = CATEGORIES.filter(c => text.includes(c.toLowerCase()));
      let moved = 0;

      if (matchedCats.length > 0) {
        result.forEach(t => {
          if (matchedCats.includes(t.category)) {
            t.action = 'move_tomorrow';
            t.due_date = tomorrow;
            moved++;
          }
        });
      } else {
        // No specific category — move the last task
        const last = result[result.length - 1];
        if (last) { last.action = 'move_tomorrow'; last.due_date = tomorrow; moved = 1; }
      }

      summary = moved > 0
        ? `Done — moved ${moved} task${moved > 1 ? 's' : ''} to tomorrow.`
        : `I left today's plan unchanged since I couldn't identify a specific category to move.`;

    } else {
      summary = `Running in Offline Mode — I couldn't fully interpret that request, so today's plan is unchanged. Try "I'm tired", "urgent meeting", or "move DSA work" for automatic adjustments.`;
    }

    return { tasks: result, summary, provider: OfflineEngine.name };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // MODULE 6 FALLBACK — AI FOLLOW-UP COACH
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Returns a warm, non-judgmental coaching message with real remaining-
   * minute math. Uses templated messages instead of AI generation.
   *
   * @param {object} params
   * @param {string} params.taskTitle
   * @param {number} params.completionPercent
   * @param {number} params.estimatedMinutes
   * @returns {{ message: string, suggestRollover: boolean, remainingMinutes: number, provider: string }}
   */
  static followUpCoach({ taskTitle, completionPercent, estimatedMinutes = 0 }) {
    const remainingMinutes = estimatedMinutes > 0
      ? Math.round((estimatedMinutes * (100 - completionPercent)) / 100)
      : 0;

    let message;

    if (completionPercent >= 100) {
      message = `🎉 You finished "${taskTitle}" — that's a win! Great work today.`;
    } else if (completionPercent >= 75) {
      message = `Almost there on "${taskTitle}" — ${completionPercent}% is genuinely solid progress.` +
        (remainingMinutes > 0
          ? ` Would you like me to move the remaining ${remainingMinutes} minutes to tomorrow?`
          : '');
    } else if (completionPercent >= 50) {
      message = `Halfway through "${taskTitle}" counts for a lot.` +
        (remainingMinutes > 0
          ? ` Want me to schedule the remaining ${remainingMinutes} minutes for tomorrow so it's not lost?`
          : '');
    } else if (completionPercent >= 25) {
      message = `Every bit of progress on "${taskTitle}" adds up.` +
        (remainingMinutes > 0
          ? ` Would you like me to move the remaining ${remainingMinutes} minutes to tomorrow?`
          : '');
    } else {
      message = `No worries about "${taskTitle}" — life happens.` +
        (remainingMinutes > 0
          ? ` Want me to reschedule the full ${remainingMinutes} minutes for tomorrow?`
          : " Let's plan it in again soon.");
    }

    return {
      message,
      suggestRollover: completionPercent < 100,
      remainingMinutes,
      provider: OfflineEngine.name
    };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // AI GOAL PLANNER FALLBACK
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Returns a sensible default set of recurring activity templates for
   * any goal. Used when the AI Goal Planner cannot reach Gemini or Groq.
   *
   * @param {object} params
   * @param {string} params.goalTitle
   * @param {number} params.deadlineDays
   * @returns {{ templates: Array, provider: string }}
   */
  static generateGoalPlan({ deadlineDays = 60 }) {
    const templates = [
      {
        title: 'DSA Practice',
        category: 'DSA',
        frequency: 'daily',
        priority: 'high',
        estimated_minutes: 45,
        notes: 'Core problem-solving practice (offline default plan).'
      },
      {
        title: 'Aptitude Practice',
        category: 'Aptitude',
        frequency: 'daily',
        priority: 'medium',
        estimated_minutes: 30,
        notes: 'Daily quantitative and logical reasoning practice (offline default plan).'
      },
      {
        title: 'Mock Test',
        category: 'Mock Tests',
        frequency: 'weekly',
        priority: 'high',
        estimated_minutes: 90,
        notes: 'Weekly full-length practice test (offline default plan).'
      },
      {
        title: 'Communication Practice',
        category: 'Communication',
        frequency: 'daily',
        priority: 'medium',
        estimated_minutes: 20,
        notes: 'Short daily speaking and interview practice (offline default plan).'
      }
    ];

    // For very tight deadlines, keep only high-priority and weekly items
    const filtered = deadlineDays < 14
      ? templates.filter(t => t.priority === 'high' || t.frequency === 'weekly')
      : templates;

    return { templates: filtered, provider: OfflineEngine.name };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // FEATURE 8 FALLBACK — WEEKLY REVIEW NARRATIVE
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Builds a short weekly review narrative directly from the deterministic
   * stats computed by db.getWeeklyReview() — no AI call required.
   *
   * @param {object} reviewData - result of db.getWeeklyReview()
   * @returns {{ narrative: string, highlightOfWeek: string, provider: string }}
   */
  static generateWeeklyReviewNarrative(reviewData) {
    const { stats, highlights, improvementAreas } = reviewData;

    let narrative =
      `This week you studied ${stats.hoursStudied} hour${stats.hoursStudied === 1 ? '' : 's'} ` +
      `across ${stats.sessionCount} session${stats.sessionCount === 1 ? '' : 's'}, ` +
      `completed ${stats.tasksCompleted} task${stats.tasksCompleted === 1 ? '' : 's'}, ` +
      `and earned ${stats.xpEarned} XP.`;

    if (stats.completionRate !== null) {
      narrative += ` That's a ${stats.completionRate}% completion rate for tasks due this week.`;
    }

    if (improvementAreas.length > 0 && !improvementAreas[0].startsWith('No major')) {
      narrative += ` One area to watch: ${improvementAreas[0].replace(/\.$/, '').toLowerCase()}.`;
    } else {
      narrative += ` Solid, consistent effort — keep it up!`;
    }

    const highlightOfWeek =
      highlights[0] || `${stats.tasksCompleted} task${stats.tasksCompleted === 1 ? '' : 's'} completed this week.`;

    return { narrative, highlightOfWeek, provider: OfflineEngine.name };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // FEATURE 1 FALLBACK — CAREER ROADMAP
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Generates a generic multi-month career roadmap when the AI is unavailable.
   *
   * @param {string} targetRole
   * @param {number} totalMonths
   * @returns {{ milestones: Array, provider: string }}
   */
  static generateCareerRoadmap(targetRole, totalMonths = 3) {
    const phaseNames = ['Foundations', 'Core Skills', 'Advanced Topics', 'Projects & Practice', 'Capstone & Job Prep'];
    const milestones = Array.from({ length: totalMonths }, (_, i) => ({
      month_number: i + 1,
      title: `Month ${i + 1}: ${phaseNames[Math.min(i, phaseNames.length - 1)]}`,
      description: i === 0
        ? `Build the core fundamentals needed to become a ${targetRole}. Focus on learning the primary tools and establishing daily practice habits.`
        : i === totalMonths - 1
        ? `Consolidate everything learned, build a portfolio-ready capstone project, and prepare for job applications or interviews.`
        : `Deepen your understanding with intermediate topics. Apply your skills to progressively complex projects.`,
      skills: i === 0
        ? ['Core syntax and fundamentals', 'Development environment setup', 'Version control with Git', 'Problem-solving basics', 'Community resources and docs']
        : i === totalMonths - 1
        ? ['System design basics', 'Interview preparation', 'Portfolio optimization', 'Code review and best practices', 'Open-source contribution']
        : ['Intermediate frameworks and libraries', 'Testing and debugging', 'Performance optimization', 'API integration', 'Design patterns'],
      projects: i === 0
        ? [`Beginner project applying ${targetRole} core concepts`]
        : i === totalMonths - 1
        ? ['Capstone portfolio project', 'Technical blog post about your learning journey']
        : [`Mid-level ${targetRole} project with real-world complexity`]
    }));

    return { milestones, provider: OfflineEngine.name };
  }

  // ═══════════════════════════════════════════════════════════════════════
  // FEATURE 9 FALLBACK — PERSONAL COACH CHAT
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Returns a context-aware templated coaching reply when the AI is
   * unavailable. Uses the coachContext object (from db.getCoachContext())
   * to personalize the response as much as possible without an AI call.
   *
   * @param {string} userMessage
   * @param {object} coachContext
   * @returns {{ reply: string, provider: string }}
   */
  static coachReply(userMessage, coachContext = {}) {
    const msg = (userMessage || '').toLowerCase();
    const ctx = coachContext;
    let reply;

    if (msg.includes('tired') || msg.includes('exhausted') || msg.includes('burnout')) {
      reply = `It's completely okay to feel tired — rest is a core part of sustainable progress. Try a lighter day: just 1-2 small tasks. Even 20 focused minutes of revision counts and keeps your streak alive.`;
    } else if (msg.includes('missed') || msg.includes('failed') || msg.includes("didn't") || msg.includes('behind')) {
      reply = `Missing tasks happens to everyone — what matters is the next move. Pick your single highest-priority pending task and spend 25 minutes on it right now. Progress is progress, no matter how small.`;
    } else if (msg.includes('exam') || msg.includes('test') || msg.includes('interview')) {
      reply = `For exam and interview prep, consistency beats last-minute cramming every time. Try three focused sessions today: one on core concepts, one on practice problems, and one short revision block.`;
    } else if (msg.includes('motivat') || msg.includes('lazy') || msg.includes("can't focus")) {
      reply = `Start with just 5 minutes on your top task — seriously, set a timer. The momentum almost always carries you much further than you expected once you begin.`;
    } else if (msg.includes('plan') || msg.includes('schedule') || msg.includes('today')) {
      const pending = ctx.todayTasksTotal - (ctx.todayTasksCompleted || 0);
      if (pending > 0) {
        reply = `You have ${pending} task${pending === 1 ? '' : 's'} remaining today. Head to the Planner page to generate an AI schedule, or use Adaptive Replanning on the Coach page to rebuild your day around your current energy level.`;
      } else {
        reply = `You're all caught up for today! Use the Goals page to check your long-term targets, or add new tasks for tomorrow on the Dashboard.`;
      }
    } else if (ctx.overdueCount > 0) {
      reply = `You have ${ctx.overdueCount} overdue task${ctx.overdueCount > 1 ? 's' : ''}. Don't try to catch up all at once — pick one, complete what you can, and use the Follow-Up Coach on the Dashboard to handle the rest compassionately.`;
    } else if (ctx.dailyScore !== undefined && ctx.dailyScore < 40) {
      const suggestion = ctx.mostProductiveCategory
        ? `${ctx.mostProductiveCategory} tasks are your strongest area — start there.`
        : 'Start with your highest-priority task.';
      reply = `Your score is a bit low today, but there's still time to turn it around. ${suggestion}`;
    } else if (ctx.activeGoals?.length > 0) {
      const g = ctx.activeGoals[0];
      reply = `Your "${g.title}" goal is ${g.progress}% complete${g.daysRemaining !== null ? ` with ${g.daysRemaining} days remaining` : ''}. Check the Goals page for specific recommendations on what to tackle next.`;
    } else {
      reply = `You're doing well — keep the momentum going! Check the Coach page for your weekly review and productivity scores, and the Goals page to track your long-term targets.`;
    }

    return { reply, provider: OfflineEngine.name };
  }
}

module.exports = OfflineEngine;